version: '2.1'
services:
  eureka:
    image: erdaoya/cloud-server-discovery
    ports:
      - "9001:9001"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_HOST: discovery
      SERVICE_PORT: 9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3


  config:
    image: erdaoya/cloud-server-config
    ports:
      - "9000:9000"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9000
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  zipkin:
    image: erdaoya/cloud-zipkin-ui
    restart: always
    ports:
      - "9012:9012"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9012
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy

  user:
    image: erdaoya/cloud-service-user
    ports:
      - "9002:9002"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9002
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy

  trade:
    image: erdaoya/cloud-service-trade
    ports:
      - "9007:9007"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9007
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
  client:
    image: erdaoya/cloud-service-client
    ports:
      - "9005:9005"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9005
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config
  gateway:
    image: erdaoya/cloud-api-gateway
    ports:
      - "9006:9006"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9006
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config

  turbine:
    image: erdaoya/cloud-turbine-dashboard
    ports:
      - "9010:9010"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9010
      REGISTRY_URL: http://discovery:9001/eureka
    depends_on:
      - eureka
      - config

  admin:
    image: erdaoya/cloud-admin-ui
    ports:
      - "9003:9003"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9003
      REGISTRY_URL: http://discovery:9001/eureka
      TURBINE_URL: http://discovery:9010/turbine.stream
    depends_on:
      - eureka

  comx:
    image: erdaoya/cloud-service-comx
    ports:
      - "9019:9019"
    network_mode: "host"
    environment:
      JAVA_OPTS: -Xmx128m
      SERVICE_PORT: 9019
      REGISTRY_URL: http://discovery:9001/eureka
#    volumes:
#        - "/www:/www"
    depends_on:
      - eureka
      - config
