hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# 重试机制
spring.cloud.loadbalancer.retry.enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  # 对当前实例的重试次数
  MaxAutoRetries: 1

#最大可用策略，即先过滤出故障服务器后，选择一个当前并发请求数最小的
ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule